version: '3'
services:
  ros-dev:
    image: ros-dev
    volumes:
     - /home:/home
     - /:/mnt/host
     - ./entry.sh:/entry.sh
     - /mnt/hdd/zlo2bp:/cache
     - $HOME/.Xauthority:/root/.Xauthority:rw
     - /tmp/.X11-unix:/tmp/.X11-unix
#     - /etc/sudoers:/etc/sudoers:ro                          # inherit sudoers settings from hosts
     
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - HOST_USER=$USER
    - HOST_UID=$UID
    - _JAVA_OPTIONS=-Duser.home=/home/$USER/    # for Java based apps, i.e. PyCharm, CLion
    - NVIDIA_VISIBLE_DEVICES=all
#    entrypoint: ["/entry.sh"]

    ipc: host

    container_name: ros
    hostname: ros-dev
    working_dir: $HOME

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined