version: '3'
services:
  ros-dev:
    image: szokelaszlo95/ros-dev
    volumes:
     - /home:/home
     - /:/mnt/host
     - /home/$USER/workspace:/workspace:rw
     - $HOME:/home/$USER
     - ./entry.sh:/entry.sh
     - $HOME/.Xauthority:/root/.Xauthority:rw
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /etc/sudoers:/etc/sudoers:ro                          # inherit sudoers settings from hosts
     - /etc/passwd:/etc/passwd:ro
     - /etc/shadow:/etc/shadow:ro
     
    environment:
    - DISPLAY=${DISPLAY}
    - HOST_USER=$USER
    - HOST_UID=$UID
    - ROS_MASTER_URI=http://192.168.1.101:11311
    - ROS_IP=192.168.0.19
    - CATKIN_WS=/workspace/catkin_ws
    - QT_X11_NO_MITSHM=1
    - NVIDIA_VISIBLE_DEVICES=all
    
    entrypoint: ["/entry.sh"]

    ipc: host
    network_mode: "host"

    container_name: ros
    hostname: ros-dev
    working_dir: $HOME

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

