version: '3'
services:
  ros-dev:
    image: ros-dev
    volumes:
     - /home:/home
     - /:/mnt/host
     - /cache/hdd/workspace:/workspace:rw
     - $HOME:/home/$USER
     - ./entry.sh:/entry.sh
     - /mnt/hdd/zlo2bp:/cache
     - /etc/krb5.conf:/etc/krb5.conf:ro                      # Mount Kerberos ticket for authentication
     - /etc/krb5.conf.d/:/etc/krb5.conf.d/:ro                # Mount Kerberos ticket for authentication?
     - $HOME/.Xauthority:/root/.Xauthority:rw
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /etc/sudoers:/etc/sudoers:ro                          # inherit sudoers settings from hosts
     - /etc/passwd:/etc/passwd:ro
     - /etc/shadow:/etc/shadow:ro
     
    environment:
    - DISPLAY=${DISPLAY}
    - HOST_USER=$USER
    - HOST_UID=$UID
    - CATKIN_WS=/workspace/catkin_ws
    - QT_X11_NO_MITSHM=1
    - NVIDIA_VISIBLE_DEVICES=all
    
    entrypoint: ["/entry.sh"]

    ipc: host

    container_name: ros
    hostname: ros-dev
    working_dir: $HOME

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
