version: '3'
services:
#     ______       _       _______     _____          _       
#   .' ___  |     / \     |_   __ \   |_   _|        / \      
#  / .'   \_|    / _ \      | |__) |    | |         / _ \     
#  | |          / ___ \     |  __ /     | |   _    / ___ \    
#  \ `.___.'\ _/ /   \ \_  _| |  \ \_  _| |__/ | _/ /   \ \_  
#   `.____ .'|____| |____||____| |___||________||____| |____| 
#                                                                                                                                                                                            

  carla_client:
    image: szokelaszlo95/carla-dev
    environment:
    - SDL_VIDEODRIVER=x11
    - DISPLAY=$DISPLAY
    - XAUTHORITY=$XAUTH
    - XAUTH=$XAUTH
    - HOST_USER=$USER
    - HOST_UID=$UID
    - QT_X11_NO_MITSHM=1
    - _JAVA_OPTIONS=-Duser.home=/home/$USER/    # for Java based apps, i.e. PyCharm, CLion
    - NVIDIA_VISIBLE_DEVICES=all
    volumes:
    - /home/$USER/:/home/$USER
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /etc/krb5.conf:/etc/krb5.conf:ro                      # Mount Kerberos ticket for authentication
    - /etc/krb5.conf.d/:/etc/krb5.conf.d/:ro                # Mount Kerberos ticket for authentication?
    - /mnt:/mnt
    - /cache/hdd:/cache
    - /tmp:/tmp
    ports:
    - "1234:22"
    links:
      - "carla_server:server"

    container_name: carla
    hostname: carla-remote-dev
    working_dir: $HOME
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: ["/entry.sh", "true"]

  carla_server:
    image: szokelaszlo95/carla_server
    environment:
      - SDL_VIDEODRIVER=offscreen
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ~/workspace:/workspace
    ports:
    - 2000-2002:2000-2002

    entrypoint: ["/bin/bash", "./CarlaUE4.sh", "-opengl", "-carla-server"]
