version: '3'
services:
#     ______       _       _______     _____          _       
#   .' ___  |     / \     |_   __ \   |_   _|        / \      
#  / .'   \_|    / _ \      | |__) |    | |         / _ \     
#  | |          / ___ \     |  __ /     | |   _    / ___ \    
#  \ `.___.'\ _/ /   \ \_  _| |  \ \_  _| |__/ | _/ /   \ \_  
#   `.____ .'|____| |____||____| |___||________||____| |____| 
#                                                                                                                                                                                            

  carla_client:
    image: carla-dev
    environment:
    - SDL_VIDEODRIVER=x11
    - DISPLAY=$DISPLAY
    - XAUTHORITY=$XAUTH
    - XAUTH=$XAUTH
    - HOST_USER=$USER
    - HOST_UID=$UID
    volumes:
#    - $XAUTH:$XAUTH
    - /home:/home
    - /home/$USER/workspace:/workspace
    - /mnt:/mnt
    - /cache:/cache
    - /tmp:/tmp
    ports:
    - 2000-2002:2000-2002
    entrypoint: /entry.sh

  carla_server:
    image: carla_server
    volumes:
#    - /cache:/cache
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - SDL_VIDEODRIVER=offscreen
    - ~/workspace:/workspace
    ports:
    - 2000-2002:2000-2002
    entrypoint: ["./CarlaUE4.sh", "-world-port", "2000", "-no-sound", "-opengl"]
